# Generated by Django 5.1.10 on 2026-05-21 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_summary', models.TextField(help_text='Structured summary of lecture content')),
                ('key_concepts', models.JSONField(default=list, help_text='List of key concepts extracted from lecture')),
                ('important_points', models.JSONField(default=list, help_text='Critical points for student comprehension')),
                ('accuracy_score', models.FloatField(blank=True, help_text='Ensemble consensus accuracy (0-100)', null=True)),
                ('model_agreement_score', models.FloatField(blank=True, help_text='Level of agreement between LLM models (0-100)', null=True)),
                ('models_used', models.JSONField(default=list, help_text='List of LLM models used in ensemble')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(help_text='Session this summary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='lectures.session')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session'], name='summaries_s_session_6d1f91_idx')],
            },
        ),
    ]
