# Generated by Django 5.1.10 on 2026-05-21 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_identifier', models.CharField(help_text='Unique identifier for student in session', max_length=100)),
                ('response_text', models.TextField(help_text="Student's verbal response (transcribed)")),
                ('audio_file', models.FileField(blank=True, help_text='Audio recording of student response', null=True, upload_to='uploads/responses/%Y/%m/%d/')),
                ('audio_duration_seconds', models.FloatField(blank=True, help_text='Duration of response audio', null=True)),
                ('evaluation_status', models.CharField(choices=[('pending', 'Pending Evaluation'), ('evaluated', 'Evaluated'), ('skipped', 'Skipped')], default='pending', help_text='Current evaluation status', max_length=20)),
                ('accuracy_score', models.FloatField(blank=True, help_text='Accuracy of response (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('completeness_score', models.FloatField(blank=True, help_text='Completeness of response (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('clarity_score', models.FloatField(blank=True, help_text='Clarity of expression (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('overall_score', models.FloatField(blank=True, help_text='Overall response score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('feedback', models.TextField(blank=True, help_text='Evaluator feedback on response')),
                ('ensemble_agreement_score', models.FloatField(blank=True, help_text='LLM ensemble agreement on evaluation (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ensemble_confidence_score', models.FloatField(blank=True, help_text='Ensemble confidence in evaluation (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(help_text='Question being responded to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questions.question')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['question', 'student_identifier'], name='responses_r_questio_5d68aa_idx'), models.Index(fields=['evaluation_status'], name='responses_r_evaluat_b7fe29_idx'), models.Index(fields=['-created_at'], name='responses_r_created_5d2f3c_idx')],
                'unique_together': {('question', 'student_identifier')},
            },
        ),
    ]
