# Generated by Django 5.1.10 on 2026-05-21 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The assessment question')),
                ('model_answer', models.TextField(help_text='Expected/model answer for this question')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Question difficulty', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order of question in session')),
                ('audio_file', models.FileField(blank=True, help_text='TTS audio file for this question', null=True, upload_to='uploads/questions/%Y/%m/%d/')),
                ('audio_duration_seconds', models.FloatField(blank=True, help_text='Duration of audio recording', null=True)),
                ('ensemble_agreement_score', models.FloatField(blank=True, help_text='LLM ensemble agreement on this question (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ensemble_confidence_score', models.FloatField(blank=True, help_text='Ensemble confidence in question quality (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(help_text='Session this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lectures.session')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['session', 'order'], name='questions_q_session_87e04b_idx'), models.Index(fields=['difficulty_level'], name='questions_q_difficu_2e0825_idx')],
            },
        ),
    ]
