# Generated by Django 5.1.10 on 2026-05-21 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_model', models.CharField(help_text='Which LLM model performed evaluation', max_length=100)),
                ('accuracy_assessment', models.TextField(help_text='LLM assessment of accuracy')),
                ('completeness_assessment', models.TextField(help_text='LLM assessment of completeness')),
                ('clarity_assessment', models.TextField(help_text='LLM assessment of clarity')),
                ('strengths', models.TextField(blank=True, help_text='Strengths identified in response')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas needing improvement')),
                ('evaluation_agreement_score', models.FloatField(blank=True, help_text='Agreement level between evaluating LLMs (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
