# Generated by Django 5.1.10 on 2026-05-21 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='response',
            field=models.OneToOneField(help_text='Response being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='responses.response'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['response'], name='evaluations_respons_9e9381_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluator_model'], name='evaluations_evaluat_2f1576_idx'),
        ),
    ]
