# Generated by Django 5.1.10 on 2026-05-21 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Lecture title/topic', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', help_text='Current session status', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total session duration in seconds', null=True)),
                ('target_question_count', models.IntegerField(default=5, help_text='Number of assessment questions to generate', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('auto_question_mode', models.BooleanField(default=True, help_text='Automatically determine question count based on content')),
                ('teaching_effectiveness_score', models.FloatField(blank=True, help_text='Teaching effectiveness score for this session (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('average_student_comprehension', models.FloatField(blank=True, help_text='Average student comprehension score for this session', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('transcript_ready', models.BooleanField(default=False, help_text='Full transcript generated')),
                ('summary_ready', models.BooleanField(default=False, help_text='Summary processing complete')),
                ('questions_ready', models.BooleanField(default=False, help_text='Questions generated')),
                ('evaluation_ready', models.BooleanField(default=False, help_text='Student responses evaluated')),
                ('results_published', models.BooleanField(default=False, help_text='Results visible to student view')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(help_text='Lecturer leading the session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lecturers.lecturer')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['lecturer', '-started_at'], name='lectures_se_lecture_c514eb_idx'), models.Index(fields=['status'], name='lectures_se_status_bc8dcb_idx'), models.Index(fields=['-started_at'], name='lectures_se_started_fd2bdd_idx')],
            },
        ),
    ]
