# Generated by Django 5.1.10 on 2026-05-21 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_effectiveness_score', models.FloatField(default=0.0, help_text='Aggregate teaching effectiveness score (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_sessions', models.IntegerField(default=0, help_text='Total lecture sessions')),
                ('average_student_comprehension', models.FloatField(default=0.0, help_text='Average student comprehension across all sessions', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('bio', models.TextField(blank=True, help_text='Lecturer bio/about')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('office_hours', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-overall_effectiveness_score'],
            },
        ),
    ]
