# Generated by Django 5.1.10 on 2026-05-21 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField(help_text='Complete lecture transcript from STT service')),
                ('total_words', models.IntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('confidence_score', models.FloatField(blank=True, help_text='Average STT confidence (0-1)', null=True)),
                ('preprocessed', models.BooleanField(default=False, help_text='Data cleaned/validated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(help_text='Session this transcript belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='lectures.session')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session'], name='transcripts_session_04a2bd_idx')],
            },
        ),
    ]
