from django.db import models
from apps.lectures.models import Session


class Summary(models.Model):
    """Structured lecture summary generated by LLM ensemble."""

    session = models.OneToOneField(
        Session,
        on_delete=models.CASCADE,
        related_name="summary",
        help_text="Session this summary belongs to",
    )
    
    # Summary content
    structured_summary = models.TextField(
        help_text="Structured summary of lecture content"
    )
    key_concepts = models.JSONField(
        default=list,
        help_text="List of key concepts extracted from lecture",
    )
    important_points = models.JSONField(
        default=list,
        help_text="Critical points for student comprehension",
    )
    
    # Quality metrics from ensemble
    accuracy_score = models.FloatField(
        null=True,
        blank=True,
        help_text="Ensemble consensus accuracy (0-100)",
    )
    model_agreement_score = models.FloatField(
        null=True,
        blank=True,
        help_text="Level of agreement between LLM models (0-100)",
    )
    
    # LLM ensemble metadata
    models_used = models.JSONField(
        default=list,
        help_text="List of LLM models used in ensemble",
    )
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["session"]),
        ]

    def __str__(self):
        return f"Summary: {self.session.title}"
